### ISSUE TITLE
Mesh grid css contains unprocessed LESS

### ISSUE THREAD

**Issue by strarsis** [linchpin/mesh#63]
On pages where a mesh grid is used, the page gets spaced horizontally including scrollbar.

The reason for this is an unprocessed less method in the final browser styles:
```css
.row {
  max-width: rem-calc(1200);
}
````
Changing max-width to e.g. 1200px resolves the issue.
